version: '3.3'
services:

  frontend:

    image: fedotovaa/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:

    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/foodgram/data/
    env_file:
      - ./.env

  backend:

    image: fedotovaa/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/django_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:

    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - media_value:/usr/share/nginx/html/media/
      - static_value:/usr/share/nginx/html/django_static/
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

volumes:
  media_value:
  static_value:
